color_theme="Default"
theme_background=False
truecolor=True
force_tty=False
presets="cpu:1:default,mem:1:default,net:1:default,proc:1:default"
vim_keys=True
rounded_corners=True
graph_symbol="braille"
graph_symbol_cpu="braille"
graph_symbol_mem="braille"
graph_symbol_net="braille"
graph_symbol_proc="braille"
shown_boxes="cpu mem net proc"
update_ms=1000
